### ISSUE TITLE
Select desidered karyotypses for phasing mutations

### ISSUE THREAD

**Issue by nicola-calonaci** [caravagnalab/CNAqc#35]
At the moment the only option for selecting karyotypes in the phasing procedure is a cut-off on the minimum number of mutations. It would be useful for the user to additionally be able to select desired karyotypes. 

For instance, I want to focus on diploid homozygous (karyotype "2:0") segments and find the multiplicity of mutations thereof.

**Comment by nicola-calonaci** [comment]
True but function "subset_by_segment_karyotype" removes the "peaks_analysis" from the CNAqc object. Is that intentional?

**Comment by caravagn** [comment]
I am sorry but I am not in favour of this because there is already a very neat way of getting the same and this means that this is unnecessary, and therefore unrequired.

```
x %>% 
   subset_by_segment_karyotype("2:0") %>% 
   advanced_phasing()
```

Instead, dropping analyses results is done for the same logic: avoiding that we have to manage complicated scenarios.

Example: 
- you have karyotype "2:1" and "1:0", you do peak analysis
- you subset to"2:1"
- your peak analysis contains results (in plots, tables etc) for "1:0" data that is no longer inside the object

How do you manage plots? And getters? etc.
